services:
  server:
    build:
      dockerfile: ./server/deployment/Dockerfile
      context: .
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./server:/usr/local/app/server
      - /usr/local/app/server/node_modules
    profiles:
      - "dev"

  server-prod:
    build:
      dockerfile: ./server/deployment/Dockerfile.prod
      context: .
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - app-logs:/usr/local/app/server/logs
      - app-files:/usr/local/app/server/files
    profiles:
      - "prod"

  db:
    image: postgres:15.3-bookworm
    env_file:
      - .env
    ports:
      - ${PGPORT}:${PGPORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 3
    volumes:
      - postgres_db:/var/lib/postgresql/data
    profiles:
      - "dev"
      - "prod"
  
  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 3
    profiles:
      - "dev"
      - "prod"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  client-prod:
    build:
      context: ./
      dockerfile: ./client/docker/Dockerfile.prod
    depends_on:
      - server-prod
    ports:
      - "${FRONTEND_PORT}:80"
    env_file:
      - .env
    profiles:
      - "prod"

  client:
    build:
      context: .
      dockerfile: ./client/docker/Dockerfile
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    env_file:
      - .env
    volumes:
      - ./client:/usr/local/app/client
      - /usr/local/app/client/node_modules
    profiles:
      - "dev"

volumes:
  postgres_db:

networks:
  default:
    name: "erp_net"
