name: Deploy Production

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  production:
    runs-on: eee-ims
    steps:
      - name: Deploy to production
        run: |
          cd /home/ubuntu
          cd bphcerp/Erp
          git pull
          docker compose --profile prod up --build -d
          docker compose exec server-prod pnpm db:migrate
          docker compose exec server-prod pnpm db:seed
